name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Simulate a Build
        run: echo 'hello youtube' > output.txt
        
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3
        with:          
          name: 'your-artifact-name'
          path: 'output.txt'
          
      - name: Create an issue
        uses: JasonEtco/create-an-issue@v2.9.1
        env:
          GITHUB_TOKEN: ${{ secrets.APROVE_TOKEN }}
          ENVIRONMENT: Dev
          RUNNUMBER: ${{ github.run_number  }}
        with:         
          filename: .github/deployment-approval.md
